### ISSUE TITLE
READ ME

### ISSUE THREAD

**Issue by ScadeBlock** [ScadeBlock/BugReport#1]
Before adding an issue, you must make sure:
+ Running on the correct Minecraft version.
+ Check Compatibility in the mod page

When you add an issue, you must say:
+ Mod/Datapack name, minecraft version
+ Your modpack, mods (In modpack,etc...) you're using if needed
+ Describe the issue

**Comment by Nyawtty** [comment]
For the mod Brutal nightmare insane difficulty I want to disable phantoms in my world they make the game unplayable i want a challenge not unplayable all the other things this mod has is fine i could care less about them but phantoms need to go they shouldnt exist in the first place everyone hates them i tryd remove them b4 i started and it doesnt work in the more tab I dont want to remove this mod but i will if i dont get some help please and ty

**Comment by ScadeBlock** [comment]
Fixed in the latest version 3.0.3

**Comment by ScadeBlock** [comment]
You can customize modifiers using : "/function cw:menu/main". Some modifiers are disabled by default, you can also turn off modifiers if you don't want

**Comment by goldenpunch101** [comment]
im gettirng some errors in configs of the pluging 4.6.4, i think that is something with how mobs use some habilities in the datapack added from the plugin.

last version
mc 1.21.1

java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 2: Unknown or incomplete command, see below for error at position 0: <--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 2: Unknown or incomplete command, see below for error at position 0: <--[HERE]
        at net.minecraft.commands.functions.CommandFunction.fromLines(CommandFunction.java:86) ~[paper-1.21.1.jar:1.21.1-133-3cb8529]
        at net.minecraft.server.ServerFunctionLibrary.lambda$reload$2(ServerFunctionLibrary.java:97) ~[paper-1.21.1.jar:1.21.1-133-3cb8529]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
[15:18:12 ERROR]: Failed to load function cw:nxf/_ignored_ssmob_6l5tcj3
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 2: Unknown or incomplete command, see below for error at position 0: <--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 2: Unknown or incomplete command, see below for error at position 0: <--[HERE]
        at net.minecraft.commands.functions.CommandFunction.fromLines(CommandFunction.java:86) ~[paper-1.21.1.jar:1.21.1-133-3cb8529]
        at net.minecraft.server.ServerFunctionLibrary.lambda$reload$2(ServerFunctionLibrary.java:97) ~[paper-1.21.1.jar:1.21.1-133-3cb8529]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
